import {
  AbstractPayKitProvider,
  CapturePaymentSchema,
  Checkout,
  CreateCheckoutSchema,
  CreateCustomerParams,
  CreatePaymentSchema,
  CreateRefundSchema,
  CreateSubscriptionSchema,
  Customer,
  HTTPClient,
  InvalidTypeError,
  NotImplementedError,
  OperationFailedError,
  PAYKIT_METADATA_KEY,
  PayKitProvider,
  Payment,
  ProviderMetadataRegistry,
  Refund,
  ResourceNotFoundError,
  schema,
  UpdateCustomerParams,
  UpdatePaymentSchema,
  ValidationError,
  WebhookEventPayload,
  WebhookHandlerConfig,
  WebhookError,
  createCheckoutSchema,
  createCustomerSchema,
  createPaymentSchema,
  createRefundSchema,
  isEmailCustomer,
  isIdCustomer,
  parseCustomerName,
  stringifyMetadataValues,
} from '@paykit-sdk/core';
import { createHmac, randomBytes } from 'crypto';
import { z } from 'zod';

export interface RedsysOptions {
  /**
   * Redsys merchant code (Ds_Merchant_MerchantCode)
   */
  merchantCode: string;
  /**
   * Redsys terminal number (Ds_Merchant_Terminal)
   */
  terminal: string;
  /**
   * Secret key for HMAC-SHA256 signing (from Redsys backend)
   */
  secretKey: string;
  /**
   * Sandbox or production environment
   * @default 'sandbox'
   */
  environment?: 'sandbox' | 'production';
  /**
   * Transaction type: "0" = immediate capture, "1" = pre-authorization
   * @default "0"
   */
  transactionType?: '0' | '1';
  /**
   * Sandbox: https://sis-t..redsys.es:25443/sis/realizarPago
   * Production: https://sis.redsys.es/sis/realizarPago
   */
  redsysUrl?: string;
}

/**
 * Redsys inSite integration
 *
 * Flow:
 * 1. createCheckout() → returns merchant parameters + signature for inSite iframe
 * 2. Frontend loads redsysV3.js, renders inSite iframe with returned params
 * 3. User enters card details in iframe → Redsys returns operationId
 * 4. createPayment(operationId) → backend calls Redsys REST API to execute
 * 5. handleWebhook() → processes server-side notifications from Redsys
 */

interface RedsysMetadata extends ProviderMetadataRegistry {
  checkout: {
    /** Currency numeric code (e.g., 978 for EUR) */
    currency?: number;
    /** Order ID generated by PayKit */
    orderId?: string;
  };
  payment: {
    /** Operation ID from inSite iframe */
    operationId?: string;
  };
}

const RedsysOptionsSchema = schema<RedsysOptions>()(
  z.object({
    merchantCode: z.string().min(1),
    terminal: z.string().min(1),
    secretKey: z.string().min(1),
    environment: z.enum(['sandbox', 'production']).default('sandbox'),
    transactionType: z.enum(['0', '1']).default('0'),
    redsysUrl: z.string().optional(),
  }),
);

const PROVIDER_NAME = 'redsys';

/** Currency code to Redsys numeric code */
const CURRENCY_MAP: Record<string, number> = {
  EUR: 978,
  USD: 840,
  GBP: 826,
  JPY: 392,
};

/** Redsys response codes */
const RESPONSE_CODES: Record<string, string> = {
  '0000': 'Transaction approved',
  '0101': 'Card expired',
  '0102': 'Card temporarily blocked',
  '0106': 'Attempts exceeded',
  '0116': 'Insufficient balance',
  '0129': 'Invalid card security code',
  '0184': 'Cardholder authentication failed',
  '0190': 'Card issuer unavailable',
  '0904': 'Merchant not registered',
};

type RedsysRawEvents = {
  [K in `redsys.${string}`]: never;
};

export class RedsysProvider
  extends AbstractPayKitProvider
  implements PayKitProvider<RedsysMetadata, never, RedsysRawEvents>
{
  private readonly opts: RedsysOptions;
  private readonly _client: HTTPClient;

  constructor(opts: RedsysOptions) {
    super(RedsysOptionsSchema, opts, PROVIDER_NAME);
    this.opts = opts;
    this._client = new HTTPClient({
      baseUrl: this._getRedsysUrl(),
      headers: { 'Content-Type': 'application/json' },
      retryOptions: { max: 3, baseDelay: 1000, debug: false },
    });
  }

  readonly providerName = PROVIDER_NAME;

  get _native(): never {
    throw new NotImplementedError(
      'Native SDK not available for Redsys. Use inSite iframe.',
      this.providerName,
      { reason: 'Redsys does not provide a JS SDK' },
    );
  }

  private _getRedsysUrl(): string {
    if (this.opts.redsysUrl) return this.opts.redsysUrl;
    return this.opts.environment === 'production'
      ? 'https://sis.redsys.es/sis/realizarPago'
      : 'https://sis-t.REDsys.es:25443/sis/realizarPago';
  }

  private _getCurrencyNum(currency: string): number {
    return CURRENCY_MAP[currency.toUpperCase()] ?? 978;
  }

  private _generateOrderId(): string {
    return randomBytes(6).toString('hex').toUpperCase();
  }

  /**
   * Build the Base64-encoded merchant parameters for inSite
   */
  private _buildMerchantParams(orderId: string, amount: number, currency: string): string {
    const currencyNum = this._getCurrencyNum(currency);
    const params: Record<string, string> = {
      DS_MERCHANT_MERCHANTCODE: this.opts.merchantCode,
      DS_MERCHANT_TERMINAL: this.opts.terminal,
      DS_MERCHANT_ORDER: orderId,
      DS_MERCHANT_AMOUNT: String(amount),
      DS_MERCHANT_CURRENCY: String(currencyNum),
      DS_MERCHANT_TRANSACTIONTYPE: this.opts.transactionType ?? '0',
      DS_MERCHANT_CONSUMERLANGUAGE: '1',
      DS_MERCHANT_PRODUCTDESCRIPTION: 'Payment',
      DS_MERCHANT_TITULAR: '',
    };

    const jsonStr = JSON.stringify(params);
    return Buffer.from(jsonStr).toString('base64');
  }

  /**
   * Generate HMAC-SHA256 signature for inSite
   *
   * Signature = HMAC-SHA256(secretKey, base64(params) + orderId)
   * Order is important: base64Params + orderId (both as-is, no separators)
   */
  private _sign(orderId: string, base64Params: string): string {
    const data = base64Params + orderId;
    return createHmac('sha256', Buffer.from(this.opts.secretKey, 'base64'))
      .update(data)
      .digest('base64')
      .replace(/\+/g, '-').replace(/\//g, '/').replace(/=+$/, '');
  }

  /**
   * Create checkout for inSite
   *
   * Returns merchant parameters and signature for the frontend iframe.
   * The frontend will load redsysV3.js and render the inSite form.
   */
  createCheckout = async (
    params: CreateCheckoutSchema<RedsysMetadata['checkout']>,
  ): Promise<Checkout> => {
    const { error, data } = createCheckoutSchema.safeParse(params);
    if (error) {
      throw ValidationError.fromZodError(error, this.providerName, 'createCheckout');
    }

    // Use orderId from metadata if provided, otherwise generate
    const orderId = data.metadata?.orderId ?? this._generateOrderId();
    const currency = data.currency ?? 'EUR';
    const amount = Math.round(data.amount);

    const merchantParams = this._buildMerchantParams(orderId, amount, currency);
    const signature = this._sign(orderId, merchantParams);

    // Return a "checkout" with the inSite parameters
    // The payment_url points to Redsys inSite URL
    return {
      id: `redsys_${orderId}`,
      customer: data.customer
        ? typeof data.customer === 'string'
          ? { id: data.customer }
          : data.customer
        : null,
      session_type: 'one_time',
      payment_url: this._getRedsysUrl(),
      products: [{ id: data.item_id, quantity: data.quantity }],
      currency,
      amount,
      subscription: null,
      metadata: {
        ...stringifyMetadataValues(data.metadata ?? {}),
        [PAYKIT_METADATA_KEY]: JSON.stringify({ orderId, currency }),
        // These are passed to frontend for inSite initialization
        redsys_merchant_params: merchantParams,
        redsys_signature: signature,
        redsys_signature_version: 'HMAC_SHA256_V1',
        redsys_merchant_code: this.opts.merchantCode,
        redsys_terminal: this.opts.terminal,
      },
    };
  };

  retrieveCheckout = async (id: string): Promise<Checkout> => {
    // Redsys doesn't have a checkout retrieval API
    throw new ResourceNotFoundError('checkout', id, this.providerName);
  };

  updateCheckout = async (
    id: string,
    _params: Parameters<typeof import('@paykit-sdk/core')['updateCheckoutSchema']>[0],
  ): Promise<Checkout> => {
    throw new NotImplementedError('updateCheckout', this.providerName, {
      futureSupport: true,
    });
  };

  deleteCheckout = async (_id: string): Promise<null> => {
    return null;
  };

  /**
   * Create payment using operation ID from inSite
   *
   * The operation ID is returned by the inSite iframe when the user
   * completes the card entry. The frontend should pass it in
   * provider_metadata.operationId.
   */
  createPayment = async (
    params: CreatePaymentSchema<RedsysMetadata['payment']>,
  ): Promise<Payment> => {
    const { error, data } = createPaymentSchema.safeParse(params);
    if (error) {
      throw ValidationError.fromZodError(error, this.providerName, 'createPayment');
    }

    const operationId = data.provider_metadata?.operationId;
    if (!operationId) {
      throw new ValidationError(
        'operationId is required for Redsys inSite payments. Pass it in provider_metadata.operationId.',
        this.providerName,
        { field: 'operationId' },
      );
    }

    // Extract orderId from metadata
    const metadataItem = JSON.parse(
      (data.metadata as Record<string, string>)?.[PAYKIT_METADATA_KEY] ?? '{}',
    );
    const orderId = metadataItem.orderId;

    // Execute the payment via Redsys REST API
    const result = await this._executePayment(orderId, operationId, data.amount, data.currency);

    if (result.Ds_Response === '0000' || String(result.Ds_Response).startsWith('00')) {
      return {
        id: result.Ds_AuthorisationCode
          ? `${orderId}_${result.Ds_AuthorisationCode}`
          : operationId,
        amount: data.amount,
        currency: data.currency,
        customer: data.customer
          ? typeof data.customer === 'string'
            ? { id: data.customer }
            : data.customer
          : null,
        status: 'succeeded',
        metadata: stringifyMetadataValues(data.metadata ?? {}),
        item_id: data.item_id,
        requires_action: false,
        payment_url: null,
      };
    }

    throw new OperationFailedError(
      `Payment failed: ${RESPONSE_CODES[String(result.Ds_Response)] ?? `Code ${result.Ds_Response}`}`,
      this.providerName,
      { cause: result },
    );
  };

  /**
   * Execute payment via Redsys REST API
   */
  private async _executePayment(
    orderId: string,
    operationId: string,
    amount: number,
    currency: string,
  ): Promise<Record<string, unknown>> {
    const currencyNum = this._getCurrencyNum(currency);
    const amountStr = String(amount);

    // Build REST request parameters
    const params: Record<string, string> = {
      DS_MERCHANT_MERCHANTCODE: this.opts.merchantCode,
      DS_MERCHANT_TERMINAL: this.opts.terminal,
      DS_MERCHANT_ORDER: orderId,
      DS_MERCHANT_AMOUNT: amountStr,
      DS_MERCHANT_CURRENCY: String(currencyNum),
      DS_MERCHANT_TRANSACTIONTYPE: this.opts.transactionType ?? '0',
      DS_MERCHANT_IDOPERACION: operationId,
    };

    const base64Params = Buffer.from(JSON.stringify(params)).toString('base64');
    const signature = this._sign(orderId, base64Params);

    const { ok, data: result } = await this._client.post<Record<string, unknown>>(
      '/',
      {
        body: JSON.stringify({
          Ds_SignatureVersion: 'HMAC_SHA256_V1',
          Ds_MerchantParameters: base64Params,
          Ds_Signature: signature,
        }),
      },
    );

    if (!ok || !result) {
      throw new OperationFailedError(
        'Redsys REST API error: request failed',
        this.providerName,
      );
    }

    return result;
  }

  retrievePayment = async (id: string): Promise<Payment | null> => {
    throw new NotImplementedError('retrievePayment', this.providerName, {
      futureSupport: true,
    });
  };

  updatePayment = async (
    id: string,
    _params: Parameters<typeof import('@paykit-sdk/core')['updatePaymentSchema']>[0],
  ): Promise<Payment> => {
    throw new NotImplementedError('updatePayment', this.providerName, {
      futureSupport: true,
    });
  };

  deletePayment = async (_id: string): Promise<null> => {
    return null;
  };

  capturePayment = async (
    id: string,
    _params: CapturePaymentSchema,
  ): Promise<Payment> => {
    if (this.opts.transactionType === '1') {
      // Pre-authorization capture
      throw new NotImplementedError('capturePayment', this.providerName, {
        futureSupport: true,
      });
    }
    throw new NotImplementedError(
      'capturePayment only available for pre-authorization (transactionType=1)',
      this.providerName,
    );
  };

  cancelPayment = async (id: string): Promise<Payment> => {
    throw new NotImplementedError('cancelPayment', this.providerName, {
      futureSupport: true,
    });
  };

  createCustomer = async (
    params: CreateCustomerParams<RedsysMetadata['customer']>,
  ): Promise<Customer> => {
    const { error, data } = createCustomerSchema.safeParse(params);
    if (error) {
      throw ValidationError.fromZodError(error, this.providerName, 'createCustomer');
    }

    const { fullName } = parseCustomerName({
      name: data.name,
      email: data.email,
    });

    return {
      id: `redsys_cust_${randomBytes(4).toString('hex')}`,
      email: data.email,
      name: fullName,
      phone: data.phone ?? '',
      metadata: {},
      created_at: new Date(),
      updated_at: null,
      custom_fields: null,
    };
  };

  retrieveCustomer = async (_id: string): Promise<Customer | null> => {
    return null;
  };

  updateCustomer = async (
    id: string,
    _params: UpdateCustomerParams<RedsysMetadata['customer']>,
  ): Promise<Customer> => {
    throw new NotImplementedError('updateCustomer', this.providerName, {
      futureSupport: true,
    });
  };

  deleteCustomer = async (_id: string): Promise<null> => {
    return null;
  };

  createSubscription = async (
    _params: CreateSubscriptionSchema<RedsysMetadata['subscription']>,
  ): Promise<never> => {
    return this._notSupported('createSubscription');
  };

  retrieveSubscription = async (_id: string): Promise<never> => {
    return this._notSupported('retrieveSubscription');
  };

  updateSubscription = async (
    _id: string,
    _params: Parameters<typeof import('@paykit-sdk/core')['updateSubscriptionSchema']>[0],
  ): Promise<never> => {
    return this._notSupported('updateSubscription');
  };

  deleteSubscription = async (_id: string): Promise<null> => {
    return this._notSupported('deleteSubscription');
  };

  cancelSubscription = async (_id: string): Promise<never> => {
    return this._notSupported('cancelSubscription');
  };

  createRefund = async (
    params: CreateRefundSchema<RedsysMetadata['refund']>,
  ): Promise<Refund> => {
    const { error, data } = createRefundSchema.safeParse(params);
    if (error) {
      throw ValidationError.fromZodError(error, this.providerName, 'createRefund');
    }

    // Refund via Redsys REST API
    const metadataItem = JSON.parse(
      (data.metadata as Record<string, string>)?.[PAYKIT_METADATA_KEY] ?? '{}',
    );
    const orderId = metadataItem.orderId;

    if (!orderId) {
      throw new ValidationError(
        'orderId not found in payment metadata',
        this.providerName,
        { field: 'orderId' },
      );
    }

    const result = await this._refundPayment(
      orderId,
      data.amount,
      data.currency,
    );

    const code = String(result.Ds_Response ?? result.Ds_Restock);
    if (code === '0000' || code.startsWith('00')) {
      return {
        id: `refund_${randomBytes(4).toString('hex')}`,
        amount: data.amount,
        currency: data.currency,
        reason: 'refund',
        metadata: {},
      };
    }

    throw new OperationFailedError(
      `Refund failed: ${RESPONSE_CODES[code] ?? `Code ${code}`}`,
      this.providerName,
      { cause: result },
    );
  };

  private async _refundPayment(
    orderId: string,
    amount: number,
    currency: string,
  ): Promise<Record<string, unknown>> {
    const currencyNum = this._getCurrencyNum(currency);

    const params: Record<string, string> = {
      DS_MERCHANT_MERCHANTCODE: this.opts.merchantCode,
      DS_MERCHANT_TERMINAL: this.opts.terminal,
      DS_MERCHANT_ORDER: orderId,
      DS_MERCHANT_AMOUNT: String(amount),
      DS_MERCHANT_CURRENCY: String(currencyNum),
      DS_MERCHANT_TRANSACTIONTYPE: '3', // Refund
    };

    const base64Params = Buffer.from(JSON.stringify(params)).toString('base64');
    const signature = this._sign(orderId, base64Params);

    const { ok, data: result } = await this._client.post<Record<string, unknown>>(
      '/',
      {
        body: JSON.stringify({
          Ds_SignatureVersion: 'HMAC_SHA256_V1',
          Ds_MerchantParameters: base64Params,
          Ds_Signature: signature,
        }),
      },
    );

    if (!ok || !result) {
      throw new OperationFailedError(
        'Redsys REST API error: refund failed',
        this.providerName,
      );
    }

    return result;
  }

  /**
   * Handle Redsys webhook notifications
   *
   * Redsys sends POST to notificationUrl with:
   * - Ds_MerchantParameters (Base64 encoded response)
   * - Ds_Signature (HMAC signature)
   * - Ds_SignatureVersion
   */
  handleWebhook = async (
    payload: WebhookHandlerConfig,
    _webhookSecret: string,
  ): Promise<Array<WebhookEventPayload<RedsysRawEvents>>> => {
    const { dataAsObject } = payload;

    // Decode merchant parameters
    const paramsBase64 = dataAsObject.Ds_MerchantParameters as string;
    if (!paramsBase64) {
      throw new WebhookError('Missing Ds_MerchantParameters', this.providerName);
    }

    const paramsJson = Buffer.from(paramsBase64, 'base64').toString('utf-8');
    const params = JSON.parse(paramsJson);

    const dsResponse = String(params.Ds_Response ?? '');
    const dsOrder = params.Ds_Order;
    const dsAmount = params.Ds_Amount;
    const dsMerchantData = params.Ds_MerchantData;

    // Verify signature
    const signature = dataAsObject.Ds_Signature as string;
    const expectedSig = this._sign(dsOrder, paramsBase64);
    const sigOk = signature === expectedSig;

    if (!sigOk) {
      throw new WebhookError('Invalid Redsys webhook signature', this.providerName);
    }

    const events: Array<WebhookEventPayload<RedsysRawEvents>> = [];

    if (dsResponse === '0000' || dsResponse.startsWith('00')) {
      // Parse customer from MerchantData
      let customerId: string | null = null;
      if (dsMerchantData) {
        try {
          const merchantDataObj = JSON.parse(
            Buffer.from(dsMerchantData, 'base64').toString('utf-8'),
          );
          customerId = merchantDataObj.customerId ?? null;
        } catch {
          // ignore
        }
      }

      const amountNum = Number(dsAmount) / 100;
      const paymentId = `${dsOrder}_${params.Ds_AuthorisationCode ?? 'unknown'}`;

      events.push(
        {
          event: 'redsys.payment.succeeded' as any,
          data: {
            order_id: dsOrder,
            amount: amountNum,
            response_code: dsResponse,
            customer_id: customerId,
          },
        },
        {
          event: 'payment.succeeded' as any,
          data: {
            id: paymentId,
            amount: amountNum,
            currency: 'EUR',
            customer: customerId ? { id: customerId } : null,
            status: 'succeeded' as const,
            metadata: {},
            item_id: null,
            requires_action: false,
            payment_url: null,
          },
        },
      );
    } else {
      events.push(
        {
          event: 'redsys.payment.failed' as any,
          data: {
            order_id: dsOrder,
            response_code: dsResponse,
            error_message: RESPONSE_CODES[dsResponse] ?? `Code ${dsResponse}`,
          },
        },
        {
          event: 'payment.failed' as any,
          data: {
            id: dsOrder,
            amount: Number(dsAmount) / 100,
            currency: 'EUR',
            customer: null,
            status: 'failed' as const,
            metadata: {},
            item_id: null,
            requires_action: false,
            payment_url: null,
          },
        },
      );
    }

    return events;
  };

  private _notSupported(method: string): never {
    throw new NotImplementedError(method, this.providerName, {
      reason: `Redsys does not support ${method}`,
    });
  }
}